# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/mainwindow.ui'
#
# Created: Sun Jan  3 17:36:16 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(1200, 548)
        self.centralWidget = QtGui.QWidget(main_window)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.webView = QtWebKit.QWebView(self.centralWidget)
        self.webView.setMinimumSize(QtCore.QSize(500, 0))
        self.webView.setMaximumSize(QtCore.QSize(500, 16777215))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayout_2.addWidget(self.webView)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_identifier = QtGui.QWidget()
        self.tab_identifier.setObjectName(_fromUtf8("tab_identifier"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_identifier)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.listview_people = QtGui.QListView(self.tab_identifier)
        self.listview_people.setObjectName(_fromUtf8("listview_people"))
        self.verticalLayout_4.addWidget(self.listview_people)
        self.widget_3 = QtGui.QWidget(self.tab_identifier)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(102, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.widget_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.widget_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.tabWidget.addTab(self.tab_identifier, _fromUtf8(""))
        self.tab_post_tree = QtGui.QWidget()
        self.tab_post_tree.setObjectName(_fromUtf8("tab_post_tree"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_post_tree)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget = QtGui.QWidget(self.tab_post_tree)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeview_post = QtGui.QTreeView(self.widget)
        self.treeview_post.setObjectName(_fromUtf8("treeview_post"))
        self.verticalLayout.addWidget(self.treeview_post)
        self.verticalLayout_3.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_post_tree, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_identifier = QtGui.QWidget()
        self.page_identifier.setObjectName(_fromUtf8("page_identifier"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_identifier)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.page_identifier)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.line_identifier = QtGui.QLineEdit(self.groupBox)
        self.line_identifier.setObjectName(_fromUtf8("line_identifier"))
        self.verticalLayout_2.addWidget(self.line_identifier)
        self.line_vorname = QtGui.QLineEdit(self.groupBox)
        self.line_vorname.setObjectName(_fromUtf8("line_vorname"))
        self.verticalLayout_2.addWidget(self.line_vorname)
        self.line_nachname = QtGui.QLineEdit(self.groupBox)
        self.line_nachname.setObjectName(_fromUtf8("line_nachname"))
        self.verticalLayout_2.addWidget(self.line_nachname)
        self.widget_2 = QtGui.QWidget(self.groupBox)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_add_people = QtGui.QPushButton(self.widget_2)
        self.button_add_people.setObjectName(_fromUtf8("button_add_people"))
        self.horizontalLayout.addWidget(self.button_add_people)
        self.verticalLayout_2.addWidget(self.widget_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_identifier)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        main_window.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(main_window)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(main_window)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        main_window.setStatusBar(self.statusBar)
        self.action_new = QtGui.QAction(main_window)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_open = QtGui.QAction(main_window)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_save_as = QtGui.QAction(main_window)
        self.action_save_as.setObjectName(_fromUtf8("action_save_as"))
        self.action_save = QtGui.QAction(main_window)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_quit = QtGui.QAction(main_window)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(_translate("main_window", "MainWindow", None))
        self.pushButton.setText(_translate("main_window", "Bearbeiten", None))
        self.pushButton_2.setText(_translate("main_window", "Löschen", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_identifier), _translate("main_window", "Personen", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_post_tree), _translate("main_window", "Post-Tree", None))
        self.groupBox.setTitle(_translate("main_window", "Bearbeiten", None))
        self.line_identifier.setPlaceholderText(_translate("main_window", "Identifier", None))
        self.line_vorname.setPlaceholderText(_translate("main_window", "Vorname", None))
        self.line_nachname.setPlaceholderText(_translate("main_window", "Nachname", None))
        self.button_add_people.setText(_translate("main_window", "Hinzufügen", None))
        self.action_new.setText(_translate("main_window", "Neu", None))
        self.action_open.setText(_translate("main_window", "Öffnen", None))
        self.action_save_as.setText(_translate("main_window", "Speichern unter...", None))
        self.action_save.setText(_translate("main_window", "Speichern", None))
        self.action_quit.setText(_translate("main_window", "Beenden", None))

from PyQt4 import QtWebKit
